version: 2

models:
  - name: stg_gold_star_counts
    description: "Star counts by repository"
    columns:
      - name: repo_name
        tests:
          - not_null
         
      - name: star_count
        tests:
          - not_null

  - name: stg_gold_event_summary
    description: "GitHub events aggregated by type and hour"
    columns:
      - name: event_type
        tests:
          - not_null
      - name: hour
        tests:
          - not_null
      - name: event_count
        tests:
          - not_null

  - name: stg_gold_push_activity
    description: "Push activity by repository and hour"
    columns:
      - name: repo_name
        tests:
          - not_null
      - name: hour
        tests:
          - not_null
      - name: push_count
        tests:
          - not_null